version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: floatchat_postgres
    environment:
      POSTGRES_DB: floatchat
      POSTGRES_USER: floatchat_user
      POSTGRES_PASSWORD: floatchat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U floatchat_user -d floatchat"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: floatchat_api
    environment:
      - DATABASE_URL=postgresql://floatchat_user:floatchat_password@postgres:5432/floatchat
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma_db
      - ARGO_DATA_PATH=/app/data/argo_netcdf/
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: floatchat_streamlit
    environment:
      - API_HOST=api
      - API_PORT=8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
